### ISSUE TITLE
Using CLI 

### ISSUE THREAD

**Issue by pauljrooney** [appiphony/strike-cli#1]
There does not appear to be an exposed option in the CLI to select a different login URL. As most developers will want to install in a development/sandbox environment (and cannot install directly into Production), there needs to be an option to specify an instance/login URL. The most obvious one would be test.salesforce.com.

**Comment by sergiopalooza** [comment]
Hello Paul,
Thank you for reaching out. I just released a patch that adds support for the test.salesforce.com URL. You can specify this URL by adding a '-s' option to your command.

I do not have access to a sandbox org myself, but I was able to test this with a DX scratch org which uses the same login URL. Please let me know if you still have issues after updating to version 0.1.9 on NPM.

Thank you,
Sergio
